version: "3.7"
services:
  flask: ## Flask Application (It's a Backend for out Nginx server). Works on http://localhost:8080
    build: ./src/backend/
    environment:
      DEBUG_MODE: "True"
      DATABASE_URL: "postgresql://kamal:simplepass@psql:5432/db_main"
      SECRET_KEY: "c498c3fc762cf7b4313b0c43463f9f58a8cc9c5341596cc4a24c9d266cee56c3"
    ports:
      - "8080:8080"
    depends_on:
      - psql
    links:
      - psql
    restart: always
    volumes:
      - type: bind
        source: ./src/backend
        target: /App
        read_only: false
  psql: ## Database for Flask Application. It works on internal Port 5432, not accessible from Host machine.
    build: ./src/db/
    environment:
      POSTGRES_PASSWORD: "simplepass"
      POSTGRES_USER: "kamal"
      POSTGRES_DB: "db_main"
    expose:
      - "5432"
    # volumes: # Uncomment it if you want to bind volume locally
    #   - type: bind
    #     source: ./src/db/data
    #     target: /var/lib/postgresql/data
    #     read_only: false
  nginx: ## Main Frontend which user is going to see. Works on http://localhost:81
    build: ./src/frontend/
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src/frontend
        target: /usr/share/nginx/html
        read_only: false
  data_generator_api: ## API server Built on Flask. Provides the random data on Nginx home page.
    build: ./src/api/
    environment:
      DEBUG_MODE: "True"
      DATABASE_URL: "sqlite:////App/data.db"
      SECRET_KEY: "c498c3fc762cf7b4313dfg64354g8a8cc9c5341596cc4a24c9d266cee56c3"
    ports:
      - "8081:8080"
    restart: always
    volumes:
      - type: bind
        source: ./src/api/
        target: /App
        read_only: false
